### PR TITLE
Update PhantomClient.js

### PR DESCRIPTION
**Pull request by tsypa**
fix requestSettings in PhantomClient.js
this commit fixes error message "Cannot set property 'ignore-ssl-errors' of undefined" when I run example-wikidive-phantom.js

### CODE REVIEW

**Comment by robcolburn** [comment]
Ah, I see the issue is that [L50](https://github.com/tsypa/node-tarantula/blob/master/lib/client/PhantomClient.js#L50) should read `this.phantomSettings` rather than `this.requestSettings`.

**Comment by tsypa** [comment]
Sorry, I hurried.
Rob, example-wikidive-phantom.js still doesn't work, it is ok?

**Comment by robcolburn** [comment]
No problem, yay, peer review.

Yeah, the Node/Phantom communication can still break down on some systems.  I'm afraid I don't know enough to know why that is.

**Comment by tsypa** [comment]
Ok, I novice in javascript, can you tell me which library (or what) is the
best choice for executing javascript code within scrapped pages?
I already tried zombiejs, but deads too often stumble upon the js code.
Please help if you can.

**Comment by robcolburn** [comment]
Hrm, well I suppose it depends on your attempting accomplish.  For example, this library, Tarantula includes two modes the default "Cheerio" mode, and the "PhantomJS" mode.

Cheerio loads the html of the page into an object, from there you can do simple tasks, like say scrape the content, and store it in a database or something.  Cheerio has the advantage of being fast and efficient to execute.

PhantomJS is a headless web-browser, so think of something like Chrome without a GUI.  This is more helpful from a testing perspective, because you can interact with javascript on that page to run unit tests, or take screen-grabs and such.

If you goal is to run client-side testing, you may want not want the overhead of Tarantula and instead use something like [CasperJS](http://casperjs.org/) which is meant for those tasks.  Or, if you like interacting with Phantom via node, you might checkout [phantomas](https://www.npmjs.org/package/phantomas) or [grunt-phantomas](https://www.npmjs.org/package/grunt-phantomas).  Those tools are a bit more mature for those purposes.

**Pull request closed without merging**
