### PR TITLE
save _oldvisit function in _brain object

### PR DESCRIPTION
**Pull request by Dahie**
I wanted to be able to use custom functions within the visit-method. In order to be able to do this to the external brain-object in the, this change saves the _oldvisit-function in the brain-object as well, to fix scoping problems.

### CODE REVIEW

**Comment by Dahie** [comment]
Hey

Any chance to get this merged in the master branch? I'd like to use tarantula as a dependency in another small project, which relies on this and it would be a shame to work around it. :)

cu
Dahie

**Comment by gpolitis** [comment]
Hello Dahie, I'm not sure I fully understand the problem here. Do you want to change the oldVisit function at runtime? Also, what kind of scoping problems did you encounter; can you provide an example?

Cheers

**Comment by Dahie** [comment]
Hey

I'm using it in this project: https://github.com/Dahie/Scraperrr.js/blob/dev/lib/scraperrr.js

I add additional functions to the `brain`-object, that are called from within the `visit`-function. (See https://github.com/Dahie/Scraperrr.js/blob/dev/lib/scraperrr.js#L93)
In your code, the `visit`-function from the external `brain`-object is saved in the temporary variable `_oldVisit`, thereby, the function loses the `brain`-context and the function-calls within fail. By saving `_oldVisit` within the `_brain`-object, the context is kept and the function calls keep working.

Hope this describes my issue. :)

**Comment by gpolitis** [comment]
I see the problem now, you are correct. Thank you for your interest in tarantula! Cheers

**Comment by Dahie** [comment]
Thank you and thanks for tarantulus! :)

**Comment by Dahie** [comment]
I really don't want to sound annoying, but can you push the changes to npm as version 0.0.2? :)

Dahie

**Comment by gpolitis** [comment]
Aaah, of course, I'm sorry I forgot! I'll do that later today.

**Comment by gpolitis** [comment]
Hey Dahie, I've bumped the package version to 0.0.2 and pushed the changes to npm.org. https://npmjs.org/package/tarantula still reports 0.0.1 as the latest version, but I think that's a caching problem. I'll check back tomorrow to see if the new version is listed. Cheers

**Pull request merged**
