### PR TITLE
catch 404 response codes

### PR DESCRIPTION
**Pull request by Dahie**
As the Todo tag is saying, this could need improvement. This change lets you continue process the current neighbors queue, even after you got a 404 from a scraped dead link.

### CODE REVIEW

**Comment by gpolitis** [comment]
Having the brain handle the errors could be another option. Would that work for you?

**Comment by Dahie** [comment]
Definitely, I just figured my patch only gives the reason why the queue failes, but doesn't continue processing yet.
I wouldn't mind a full fix instead of my patching. :) 

Thanks for the quick response. :+1:

**Comment by gpolitis** [comment]
Great, then I'll try to provide a more general fix later today. I'll let you know when it's done, so you can tell me what you think and if it fits your needs (i.e. it doesn't break your code). Cheers

**Comment by gpolitis** [comment]
I guess there's no urgent need for finer error handling right now and your patch works fine, so I merged it. I uploaded version 0.0.4 to npmjs.

**Pull request merged**
